import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/Header"
import "./globals.css";
import Footer from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <head>
        {/* Add your head content here */}
      </head>
      <body className={inter.className}>
      <Header />
        {children}
        <Footer />
      </body>

    </html>
  );
}
